export const GETPRODUCT = "GETPRODUCT"
export const CREATEPRODUCT = "CREATEPRODUCT"
export const UPDATEPRODUCT = "UPDATEPRODUCT"
export const DELETEPRODUCT = "DELETEPRODUCT"

export const ADD_TO_CART = "ADD_TO_CART"